events {}

http {
  server {
    listen 80;

    # Route Supabase REST API → PostgREST
    location /rest/v1/ {
      rewrite ^/rest/v1/(.*)$ /$1 break;
      proxy_pass http://172.19.0.4:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Authorization $http_authorization;
      proxy_pass_header Content-Type;
    }
  }
}
