#!/usr/bin/env bash
# Generated by dev-core worktreeScaffold — do not edit by hand.
# Concerns: env-files, npm-install-warmup, lefthook-hookspath-fix
# Re-generate with: /stack-setup --force (or /env-setup retrofit)
set -euo pipefail

# ─── env-files ──────────────────────────────────────────
# copy .env.example → .env if missing
if [ -f .env.example ] && [ ! -f .env ]; then
  cp .env.example .env
  echo "worktree-setup: created .env from .env.example"
fi

# ─── npm-install-warmup ──────────────────────────────────────────
"${PM:-npm}" install

# ─── lefthook-hookspath-fix ──────────────────────────────────────────
# in worktrees, lefthook installs core.hooksPath relative to the worktree git dir (wrong —
# git uses the common dir for hooks). unset so git falls back to the default hooks path.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
GIT_COMMON_DIR=$(git rev-parse --git-common-dir 2>/dev/null)
if [ "${GIT_DIR}" != "${GIT_COMMON_DIR}" ]; then
  git config --unset-all core.hooksPath 2>/dev/null || true
fi
