#!/usr/bin/env bash
# Generated by dev-core worktreeScaffold — do not edit by hand.
# Concerns: env-files, npm-install-warmup, lefthook-hookspath-fix
# Re-generate with: /stack-setup --force (or /env-setup retrofit)
set -euo pipefail

# ─── env-files ──────────────────────────────────────────
# noop — env files stay in worktree after teardown
:

# ─── npm-install-warmup ──────────────────────────────────────────
:

# ─── lefthook-hookspath-fix ──────────────────────────────────────────
:
