name: ci

on:
  push:
    branches:
      - feature/react
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - uses: nrwl/nx-set-shas@v4

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "matthieu.tavian@gmail.com"
          git config --global user.name "tavianm"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -r=https://github.com/tavianm/omf-therapie.git -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
