/**
 * ⚠️  AUTO-GENERATED by scripts/generate-build-env.mjs at build time.
 * DO NOT EDIT — changes will be overwritten on the next `npm run build`.
 *
 * Snapshots Netlify's build-only env vars (CONTEXT, COMMIT_REF) so they
 * survive into the function runtime. See the generator script for the full
 * rationale (Netlify does NOT expose these at runtime by default).
 *
 * Generated for: CONTEXT="development" COMMIT_REF="dev"
 */

export const BUILD_CONTEXT: string = "development";
export const BUILD_COMMIT_REF: string = "dev";
